mysite/blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name ='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$',PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(),name='post_month_archive'),

    # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(),name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
]

mysite/bookmark/urls.py
from django.conf.urls import url
from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
    # Class - based views
    url(r'^$', BookmarkLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)', BookmarkDV.as_view(), name='detail'),
]

mysite/facebook/urls.py
from django.conf.urls import url
from facebook.views import FaceBookView

urlpatterns = [
    # Class - based views
    url(r'^$', FaceBookView.as_view()),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from quickstart import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^facebook/', include('facebook.urls', namespace='facebook')),
]

mysite/blog/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode= True, help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now_add=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

mysite/bookmark/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible


# Create your models here.

@python_2_unicode_compatible
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique = True)

    def __str__(self):
        return self.title

mysite/facebook/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mysite/blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView

from blog.models import Post

# Create your views here.

# -- ListVIew
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

# -- DetailView
class PostDV(DetailView):
    model = Post

# -- ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'

mysite/bookmark/views.py
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark
# Create your views here.


# -- ListView
class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

mysite/facebook/views.py
import json, requests, random, re
from pprint import pprint

from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from django.http import HttpResponse
from django.utils.decorators import method_decorator

#  ------------------------ Fill this with your page access token! -------------------------------
PAGE_ACCESS_TOKEN = "EAAZAtEmJIqfUBAFZB8wOgjZChKgGkZCLtV65JmVbbQPSUkI1ZAQIgTVds2yhJTG8Ya8FScZAurHxD48kT1AVu6QUaZBuI3ZCHobZBWoxfUcNxBz4SZCxLZCVbQ4lqAkp4Wn4xbU0HaTKOTTdOjUe4uraQfn5YDHNpB3ku7LQ6zGSc8hpQZDZD"
VERIFY_TOKEN = "WEBHOOK"

jokes = {'lee': ["""My name is Lee hong kyu"""],
         'seo': ["""Seo Mina is beautiful"""],
         'aq': ["""You are Creativestudio AQ"""]}


# Helper function
def post_facebook_message(fbid, recevied_message):
    # Remove all punctuations, lower case the text and split it based on space
    tokens = re.sub(r"[^a-zA-Z0-9\s]", ' ', recevied_message).lower().split()
    joke_text = ''
    for token in tokens:
        if token in jokes:
            joke_text = random.choice(jokes[token])
            break
    if not joke_text:
        joke_text = "I didn't understand! Send 'lee', 'seo', 'aq'."

    user_details_url = "https://graph.facebook.com/v2.6/%s" % fbid
    user_details_params = {'fields': 'first_name,last_name,profile_pic', 'access_token': PAGE_ACCESS_TOKEN}
    user_details = requests.get(user_details_url, user_details_params).json()
    joke_text = user_details['first_name'] + '..! ' + joke_text

    post_message_url = 'https://graph.facebook.com/v2.6/me/messages?access_token=%s' % PAGE_ACCESS_TOKEN
    response_msg = json.dumps({"recipient": {"id": fbid}, "message": {"text": joke_text}})
    status = requests.post(post_message_url, headers={"Content-Type": "application/json"}, data=response_msg)
    pprint(status.json())


# Create your views here.

class FaceBookView(generic.View):
    def get(self, request, *args, **kwargs):
        if self.request.GET['hub.verify_token'] == VERIFY_TOKEN:
            return HttpResponse(self.request.GET['hub.challenge'])
        else:
            return HttpResponse('Error, invalid token')

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return generic.View.dispatch(self, request, *args, **kwargs)

    # Post function to handle Facebook messages
    def post(self, request, *args, **kwargs):
        # Converts the text payload into a python dictionary
        incoming_message = json.loads(self.request.body.decode('utf-8'))
        # Facebook recommends going through every entry since they might send
        # multiple messages in a single call during high load
        for entry in incoming_message['entry']:
            for message in entry['messaging']:
                # Check to make sure the received call is a message call
                # This might be delivery, optin, postback for other events
                if 'message' in message:
                    # Print the message to the terminal
                    pprint(message)
                    # Assuming the sender only sends text. Non-text messages like stickers, audio, pictures
                    # are sent as attachments and must be handled accordingly.
                    post_facebook_message(message['sender']['id'], message['message']['text'])
        return HttpResponse()

mysite/quickstart/views.py
from django.contrib.auth.models import User, Group
from rest_framework import viewsets, status
from quickstart.serializers import UserSerializer, GroupSerializer


from rest_framework.decorators import api_view
from rest_framework.response import Response

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

mysite/blog/templates/blog/post_all.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Post_all</title>
</head>
<body>
<h1>Blog List</h1>

{% for post in posts %}
    <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
    {{ post.modify_date|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}

<br/>
<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page = {{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page.obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page = {{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>
</div>
</body>
</html>

mysite/blog/templates/blog/post_archive.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Post Archive</title>
</head>
<body>
<h1>Post Archive</h1>
<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a>
        </li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{post.get_absolute_url }}"><stong>{{post.title}}</stong></a></li>
        {% endfor %}
    </ul>
</div>

</body>
</html>

mysite/blog/templates/blog/post_archive_day.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Post Archive Day</title>
</head>
<body>

<h1>Post Archive for {{ day|date:"N, d Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ ost.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</body>
</html>

mysite/blog/templates/blog/post_archive_month.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Post Archive Month</title>
</head>
<body>


<h1>Post Archive for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ ost.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</body>
</html>

mysite/blog/templates/blog/post_archive_year.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Post Archive Year</title>
</head>
<body>
<h1>Post Archive Year</h1>

<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_month_archive year|date:'Y' date|date:'b' %}">
            {{date|date:"F"}}
        </a>
    </li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ ost.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

mysite/blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Post Detail</title>
</head>
<body>
    <h2>{{ object.title }}</h2>

<p class="other_posts">
    {% if object.get_previous_by_modify_date %}
    <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post"> &laquo;--{{ object.get_previous_post }}</a>
    {% endif %}

    {% if object.get_next_by_modify_date %}
    | <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">{{ object.get_next_post }}--&raquo;</a>
    {% endif %}
</p>

<p class="date">{{ object.modify_date|date:"j F Y" }}</p>
<br/>

<div class="body">
    {{ object.content|linebreaks }}
</div>
</body>
</html>

mysite/bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Django Bookmark Detail</title>
</head>
<body>

    <div id=""content">
        <h1>{{ object.title }}</h1>


    <ul>
        <li>URL : <a href="{{ object.url}}">{{object.url}}</a></li>
    </ul>
    </div>

</body>
</html>

mysite/bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Django Bookmark List</title>
</head>

<body>
    <div id="content">

        <h1>Bookmark List</h1>

        <ul>
            {% for bookmark in object_list %}
                <li><a href="{% url 'detail' bookmark.id %}">{{ bookmark }}</a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>